"""
Quick Reference: Bonus Life System

A comprehensive 1-page reference for the bonus life mechanic.
"""

def print_reference():
    print("╔" + "═" * 78 + "╗")
    print("║" + " " * 25 + "BONUS LIFE SYSTEM" + " " * 36 + "║")
    print("╚" + "═" * 78 + "╝")
    print()
    
    print("┌─ CORE MECHANIC ─────────────────────────────────────────────────────────────┐")
    print("│                                                                              │")
    print("│  Every 7 correct answers in a row → +1 bonus life 💚                        │")
    print("│  Maximum: 2 bonus lives (5 total lives: 3 base + 2 bonus)                   │")
    print("│                                                                              │")
    print("└──────────────────────────────────────────────────────────────────────────────┘")
    print()
    
    print("┌─ PROGRESSION TABLE ─────────────────────────────────────────────────────────┐")
    print("│                                                                              │")
    print("│  Streak   Bonus Lives   Total Lives   Display                               │")
    print("│  ──────   ───────────   ───────────   ──────────────────                    │")
    print("│    0-6         0            3         ❤️❤️❤️                                 │")
    print("│      7         1            4         ❤️❤️❤️💚                               │")
    print("│   8-13         1            4         ❤️❤️❤️💚                               │")
    print("│     14         2            5         ❤️❤️❤️💚💚 (MAX)                       │")
    print("│    21+         2            5         ❤️❤️❤️💚💚 (capped)                    │")
    print("│                                                                              │")
    print("└──────────────────────────────────────────────────────────────────────────────┘")
    print()
    
    print("┌─ VISUAL INDICATORS ─────────────────────────────────────────────────────────┐")
    print("│                                                                              │")
    print("│  HUD Display:          Lives: ❤️❤️💚                                         │")
    print("│  ↑                     ├─────┘ ← Red = Base lives                           │")
    print("│  └─ Shows in status    └─────── Green = Bonus lives                         │")
    print("│     bar at top                                                               │")
    print("│                                                                              │")
    print("│  Life Granted Message: \"Correcte! +1100 💚+1 VIDA!\"                         │")
    print("│                         ↑       ↑    ↑         ↑                            │")
    print("│                         │       │    │         └─ Emoji indicator            │")
    print("│                         │       │    └─────────── Green heart                │")
    print("│                         │       └──────────────── Score bonus                │")
    print("│                         └──────────────────────── Standard message           │")
    print("│                                                                              │")
    print("└──────────────────────────────────────────────────────────────────────────────┘")
    print()
    
    print("┌─ GAMEPLAY IMPACT ───────────────────────────────────────────────────────────┐")
    print("│                                                                              │")
    print("│  Base Game (3 lives):                                                        │")
    print("│  ❤️❤️❤️ → Mistake → ❤️❤️ → Mistake → ❤️ → Mistake → 💀 GAME OVER            │")
    print("│                                                                              │")
    print("│  With 1 Bonus Life (4 lives):                                               │")
    print("│  ❤️❤️❤️💚 → Mistake → ❤️❤️💚 → Mistake → ❤️💚 → Mistake → 💚                 │")
    print("│           → Mistake → 💀 GAME OVER                                           │")
    print("│                                                                              │")
    print("│  With 2 Bonus Lives (5 lives - MAX):                                        │")
    print("│  ❤️❤️❤️💚💚 → Mistake → ❤️❤️💚💚 → Mistake → ❤️💚💚 → Mistake → 💚💚           │")
    print("│            → Mistake → 💚 → Mistake → 💀 GAME OVER                           │")
    print("│                                                                              │")
    print("└──────────────────────────────────────────────────────────────────────────────┘")
    print()
    
    print("┌─ KEY RULES ─────────────────────────────────────────────────────────────────┐")
    print("│                                                                              │")
    print("│  ✓ Lives earned at exactly streak 7 and 14                                  │")
    print("│  ✓ Wrong answer or timeout resets streak to 0                               │")
    print("│  ✓ Bonus lives don't reset between rounds                                   │")
    print("│  ✓ Maximum 2 bonus lives (no more at streak 21+)                            │")
    print("│  ✓ Game over when mistakes >= (base_lives + bonus_lives)                    │")
    print("│  ✓ Practice mode: bonus lives earned but no game over                       │")
    print("│                                                                              │")
    print("└──────────────────────────────────────────────────────────────────────────────┘")
    print()
    
    print("┌─ STRATEGY TIPS ─────────────────────────────────────────────────────────────┐")
    print("│                                                                              │")
    print("│  1. Prioritize accuracy in early rounds (easier timing)                     │")
    print("│  2. Target 7 correct first → safety buffer earned                           │")
    print("│  3. Push for 14 correct → maximum lives available                           │")
    print("│  4. Bonus lives = room for risk in hard late-game                           │")
    print("│  5. One mistake with 0 bonus lives = high pressure                          │")
    print("│  6. One mistake with 2 bonus lives = still comfortable                      │")
    print("│                                                                              │")
    print("└──────────────────────────────────────────────────────────────────────────────┘")
    print()
    
    print("┌─ TECHNICAL DETAILS ─────────────────────────────────────────────────────────┐")
    print("│                                                                              │")
    print("│  GameState Properties:                                                       │")
    print("│    • base_lives = 3                                                          │")
    print("│    • bonus_lives = 0-2 (earned through play)                                │")
    print("│    • lives_per_streak = 7 (configurable)                                    │")
    print("│    • max_bonus_lives = 2 (configurable)                                     │")
    print("│                                                                              │")
    print("│  Life Grant Logic:                                                           │")
    print("│    if (streak % 7 == 0) and (bonus_lives < 2):                              │")
    print("│        bonus_lives += 1                                                      │")
    print("│                                                                              │")
    print("│  Game Over Check:                                                            │")
    print("│    total_lives = base_lives + bonus_lives                                    │")
    print("│    game_over = mistakes >= total_lives                                       │")
    print("│                                                                              │")
    print("└──────────────────────────────────────────────────────────────────────────────┘")
    print()
    
    print("┌─ TESTING ───────────────────────────────────────────────────────────────────┐")
    print("│                                                                              │")
    print("│  Run Tests:                                                                  │")
    print("│    python test_bonus_lives.py          # Unit tests                         │")
    print("│    python test_practice_mode_logic.py  # Practice mode compat               │")
    print("│                                                                              │")
    print("│  Documentation:                                                              │")
    print("│    python BONUS_LIVES_GUIDE.py         # Full guide                         │")
    print("│    python BONUS_LIFE_REFERENCE.py      # This reference                     │")
    print("│                                                                              │")
    print("└──────────────────────────────────────────────────────────────────────────────┘")
    print()

if __name__ == '__main__':
    print_reference()
