"""
Bonus Life System Demo

This demonstrates the new bonus life mechanic:
- Every 7 correct answers in a row grants +1 life
- Maximum of +2 bonus lives (5 lives total)
- Visual indicators in HUD with heart emojis
"""

def print_demo():
    print("=" * 80)
    print("BONUS LIFE SYSTEM - NEW FEATURE")
    print("=" * 80)
    print()
    
    print("📋 HOW IT WORKS:")
    print("-" * 80)
    print("  • Start with 3 lives (base)")
    print("  • Every 7 correct answers in a row → +1 life 💚")
    print("  • Maximum: 5 lives total (3 base + 2 bonus)")
    print("  • Wrong answer or timeout resets streak to 0")
    print()
    
    print("🎯 PROGRESSION:")
    print("-" * 80)
    print("  Streak  0: ❤️❤️❤️       (3 lives - starting)")
    print("  Streak  7: ❤️❤️❤️💚     (4 lives - first bonus!)")
    print("  Streak 14: ❤️❤️❤️💚💚   (5 lives - max!)")
    print("  Streak 21: ❤️❤️❤️💚💚   (5 lives - capped)")
    print()
    
    print("📊 HUD DISPLAY:")
    print("-" * 80)
    print("Normal mode shows lives with heart emojis:")
    print()
    print("  Before earning bonus lives:")
    print("    Lives: ❤️❤️❤️")
    print()
    print("  After 7 correct (1 mistake used):")
    print("    Lives: ❤️❤️💚")
    print()
    print("  After 14 correct (no mistakes):")
    print("    Lives: ❤️❤️❤️💚💚")
    print()
    print("  Color Legend:")
    print("    ❤️  Red hearts = Base lives remaining")
    print("    💚  Green hearts = Bonus lives from streaks")
    print()
    
    print("💡 STRATEGY TIPS:")
    print("-" * 80)
    print("  1. Focus on accuracy to build your streak")
    print("  2. First 7 correct answers are crucial - earn that buffer!")
    print("  3. With 2 bonus lives, you get 5 mistakes total instead of 3")
    print("  4. Use early game (easier timing) to build your life reserve")
    print("  5. Bonus lives let you survive the harder late-game challenges")
    print()
    
    print("🎮 GAMEPLAY IMPACT:")
    print("-" * 80)
    print()
    print("  WITHOUT bonus lives:")
    print("    ❤️❤️❤️ → ❤️❤️ → ❤️ → 💀 GAME OVER")
    print("    (3 mistakes = game over)")
    print()
    print("  WITH 2 bonus lives earned:")
    print("    ❤️❤️❤️💚💚 → ❤️❤️💚💚 → ❤️💚💚 → 💚💚 → 💚 → 💀 GAME OVER")
    print("    (5 mistakes = game over)")
    print()
    
    print("📝 EXAMPLES:")
    print("-" * 80)
    print()
    print("  Scenario 1: Perfect Start")
    print("    • Get 7 correct → +1 life (4 total)")
    print("    • Make 1 mistake → Still have 3 lives left")
    print("    • Continue playing with safety buffer")
    print()
    print("  Scenario 2: Expert Run")
    print("    • Get 14 correct → +2 lives (5 total)")
    print("    • Make 2 mistakes → Still have 3 lives left")
    print("    • Maximum forgiveness for late-game difficulty")
    print()
    print("  Scenario 3: Comeback Potential")
    print("    • Start with 2 mistakes (1 life left)")
    print("    • Rally with 7 correct answers → +1 bonus life")
    print("    • Now have 2 lives to work with again!")
    print()
    
    print("⚡ WHEN LIFE IS GRANTED:")
    print("-" * 80)
    print("  You'll see a special message:")
    print("    \"Correcte! +1100 💚+1 VIDA!\"")
    print()
    print("  The HUD immediately updates to show the new heart")
    print()
    
    print("🎓 PRACTICE MODE:")
    print("-" * 80)
    print("  • Practice mode has unlimited mistakes (no game over)")
    print("  • Bonus lives still earned and tracked")
    print("  • Good for learning optimal strategies")
    print()
    
    print("=" * 80)
    print("PLAY NOW TO EXPERIENCE THE NEW SYSTEM!")
    print("=" * 80)
    print()
    print("Run: python game_propera_parada.py")
    print()

if __name__ == '__main__':
    print_demo()

