"""
Mode Comparison Demo

Run this to see feature differences between normal and practice modes.
"""

def print_comparison():
    print("=" * 80)
    print("PRÒXIMA PARADA - MODE COMPARISON")
    print("=" * 80)
    print()
    
    print("┌─────────────────────────┬──────────────────────┬──────────────────────┐")
    print("│ Feature                 │ Normal Mode          │ Practice Mode        │")
    print("├─────────────────────────┼──────────────────────┼──────────────────────┤")
    print("│ Game Over               │ After 3 mistakes     │ Never                │")
    print("│ Error Counter           │ X/3 (limited)        │ X (unlimited)        │")
    print("│ High Score File         │ high_score.json      │ high_score_practice  │")
    print("│ Title Color             │ Green                │ Blue                 │")
    print("│ Title Text              │ PRÒXIMA PARADA       │ PRÒXIMA PARADA       │")
    print("│                         │                      │ [PRÀCTICA]           │")
    print("│ Difficulty Scaling      │ Yes (streak-based)   │ Yes (streak-based)   │")
    print("│ Time Pressure           │ 3.2s → 2.2s          │ 3.2s → 2.2s          │")
    print("│ Drop Radius             │ 50px → 38px          │ 50px → 38px          │")
    print("│ Animations              │ All enabled          │ All enabled          │")
    print("│ Tutorial                │ Yes                  │ Yes                  │")
    print("│ Best For                │ Competitive play     │ Learning & practice  │")
    print("└─────────────────────────┴──────────────────────┴──────────────────────┘")
    print()
    
    print("USAGE EXAMPLES:")
    print("─" * 80)
    print()
    print("1. Normal Mode (Default)")
    print("   python game_propera_parada.py")
    print("   OR")
    print("   from game_propera_parada import ProximaParadaApp")
    print("   app = ProximaParadaApp()")
    print("   app.run()")
    print()
    
    print("2. Practice Mode")
    print("   python test_practice_mode.py")
    print("   OR")
    print("   from game_propera_parada import ProximaParadaApp")
    print("   app = ProximaParadaApp(practice_mode=True)")
    print("   app.run()")
    print()
    
    print("3. Practice Mode with Fixed Seed (Reproducible)")
    print("   from game_propera_parada import ProximaParadaApp")
    print("   app = ProximaParadaApp(practice_mode=True, random_seed=42)")
    print("   app.run()")
    print()
    
    print("4. Normal Mode with Fixed Seed (Testing)")
    print("   from game_propera_parada import ProximaParadaApp")
    print("   app = ProximaParadaApp(random_seed=42)")
    print("   app.run()")
    print()
    
    print("=" * 80)
    print("PRACTICE MODE BENEFITS")
    print("=" * 80)
    print()
    print("✓ Learn station sequences without pressure")
    print("✓ Experiment with strategies")
    print("✓ Build muscle memory for drop accuracy")
    print("✓ Understand difficulty progression")
    print("✓ Track improvement over unlimited rounds")
    print("✓ Separate high scores won't affect competitive records")
    print()
    
    print("=" * 80)
    print("WHEN TO USE EACH MODE")
    print("=" * 80)
    print()
    print("Use NORMAL MODE when:")
    print("  • You want competitive gameplay")
    print("  • You're ready to beat high scores")
    print("  • You enjoy the challenge of limited mistakes")
    print("  • You want to test your mastery")
    print()
    print("Use PRACTICE MODE when:")
    print("  • You're learning the game for the first time")
    print("  • You want to memorize station sequences")
    print("  • You're testing strategies without consequences")
    print("  • You want to improve without stress")
    print("  • You're warming up before competitive play")
    print()
    print("=" * 80)

if __name__ == '__main__':
    print_comparison()

